# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hd5j1ASIAVIqMOWyoMUBFPVM4X2e8kS0
"""

class Dog:

    species = "Canis familiaris"


    def __init__(self, breed, age):
        self.breed = breed
        self.age = age

    def display_details(self):
        print("Breed:", self.breed)
        print("Age:", self.age)
        print("Species:", Dog.species)
        print("---------------------")



dog1 = Dog("Labrador", 3)
dog2 = Dog("German Shepherd", 5)


dog1.display_details()
dog2.display_details()